### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by carton04** [carton04/protospace-38626#1]
https://protospace-38626.herokuapp.com/

**Comment by ghost** [comment]
@carton04 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

**コメント機能**
- [ ] **コメントを投稿すると、投稿したコメントとその投稿者名が、
対象プロトタイプの詳細ページにのみ表示されること**
コメントを投稿すると、コメントと「コメントの投稿者名」ではなく、
プロトタイプの投稿者名が表示されております。
コメントを投稿したユーザーの名前が表示されるようにしましょう。


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
　https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by carton04** [comment]
該当箇所修正したので確認お願いします

**Comment by snkw-works** [comment]
@carton04  さん、お待たせいたしました。修正とご提出ありがとうございます。
正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう！
